services:
  backend:
    image: mirco-blog-backend
    volumes:
      - .:/micro-blog-backend/
    ports:
      - "5500:4500"
    networks:
      - blog-network

networks:
  auth-network:
    driver: bridge
